services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"

  redis:
    image: 'redis:latest'
    ports:
      - '6380:6379'
    volumes:
      - 'redis-data:/data'

  # myapp:
  #   image: myapp
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - "ASPNETCORE_URLS=http://+:80;https://+:443"
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=YourPassword
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  #   ports:
  #     - "5282:80"
  #     - "5283:443"
  #   depends_on:
  #     - mongodb
  #     - redis


volumes:
  mongodbdata:
  redis-data:
