version: '3.8'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"
  redis:
    image: 'redis:latest'
    ports:
      - '6380:6379'
    volumes:
      - 'redis-data:/data'
volumes:
  mongodbdata:
  redis-data:
